### ISSUE TITLE
JPEG化したもののみ not valid

### ISSUE THREAD

**Issue by fgophi** [fgophi/fgosccnt#101]
```
$ fgosccnt ../Screenshot_20200402-224458.png
filename,ドロ数,QP(+9400),礼装,鉄杭,剣秘,ポイント(+600),ポイント(+1800)
../Screenshot_20200402-224458.png,20+,1,0,1,1,15,3
```
```
$ fgosccnt Screenshot_20200402-224458_R.jpg
filename,ドロ数
Screenshot_20200402-224458_R.jpg: not valid,
```

![Screenshot_20200402-224458_R](https://user-images.githubusercontent.com/62515228/87399952-1d72a980-c5f3-11ea-8e49-56c1fc3f58d1.jpg)

**Comment by fgophi** [comment]
```
$ fgosccnt Screenshot_20200402-224458_R.jpg  -d
(略)
[Item6 Information]
"ポイント":np.array([[252, 7, 150, 164, 219, 120, 154, 20]], dtype='uint8'),
BONUS NORMAL読み込み: (??11)
BONUS SMALL読み込み: (+600)
BONUS TINY読み込み: (x?00)
フォントサイズ: -1
Bonus Font Size: -1
Bonus:
margin_right: 15
Traceback (most recent call last):
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 1711, in <module>
    csvfieldnames, outputcsv = get_output(inputs, args.debug)
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 1611, in get_output
    sc = ScreenShot(img_rgb, svm, svm_chest, svm_card, fileextention, debug)
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 421, in __init__
    self.items.append(Item(item_img_rgb, item_img_gray, svm, svm_card, fileextention, mode, debug))
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 778, in __init__
    self.ocr_digit(mode, debug)
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 1308, in ocr_digit
    self.dropnum =  self.detect_white_char(base_line, margin_right, font_size, debug=debug) + self.dropnum
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 1132, in detect_white_char
    line = self.get_number(base_line, margin_right, font_size)
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 1066, in get_number
    result = self.read_char(pt)
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 1250, in read_char
    tmpimg = cv2.resize(tmpimg, (win_size))
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed)!ssize.empty() in function 'cv::re
size'
```

**Comment by fgophi** [comment]
直線検出で内側の直線が検出されず左右両方に3ptのフチができているためgamescreenに6ptのずれが生じてしまっている

![image](https://user-images.githubusercontent.com/62515228/87411810-32efcf80-c603-11ea-8192-dafbc212f663.png)

そのため一番右に位置するItem6での誤差がエラーを産むことになった
![image](https://user-images.githubusercontent.com/62515228/87412050-7cd8b580-c603-11ea-9c6d-491e32f36db2.png)

フチを除去する方策が必要
