### ISSUE TITLE
JPEG化したスクショで not valid

### ISSUE THREAD

**Issue by fgophi** [fgophi/fgosccnt#104]
```
$ fgosccnt Screenshot_20200313-195743_R.jpg
filename,ドロ数
Screenshot_20200313-195743_R.jpg: not valid,
```
![Screenshot_20200313-195743_R](https://user-images.githubusercontent.com/62515228/87425036-f7133500-c617-11ea-90dd-7b2690a34f38.jpg)

**Comment by fgophi** [comment]
pageinfo.py のバグ

```
pageinfo.CannotGuessError: 幅の誤差が大きすぎます: delta = 13, entire_width = 56, actual_width = 43
$ python ../pageinfo.py  Screenshot_20200313-195743_R.jpg
Traceback (most recent call last):
  File "../pageinfo.py", line 437, in <module>
    main(args)
  File "../pageinfo.py", line 393, in main
    result = look_into_file(filename, args)
  File "../pageinfo.py", line 378, in look_into_file
    pagenum, pages, lines = guess_pageinfo(im, args.debug_sc, debug_sc_image)
  File "../pageinfo.py", line 347, in guess_pageinfo
    pages = guess_pages(asr_w, asr_h, esr_w, esr_h)
  File "../pageinfo.py", line 154, in guess_pages
    raise CannotGuessError(
__main__.CannotGuessError: 幅の誤差が大きすぎます: delta = 13, entire_width = 56, actual_width = 43

$ python ../pageinfo.py  ../Screenshot_20200313-195743.png
../Screenshot_20200313-195743.png,1,2,4
```
