### ISSUE TITLE
JPEG化したスクショでnot valid

### ISSUE THREAD

**Issue by fgophi** [fgophi/fgosccnt#109]
```
$ fgosccnt  IMG_7915_R.JPG
filename,ドロ数
IMG_7915_R.JPG: not valid,
```
```
$ fgosccnt  ../IMG_7915.PNG
filename,ドロ数,QP(+6400),礼装,鉄杭,ノーマルダイス,ライフカウンター(x3),ポイント
ジェム(x3),マーカーハウス(x3)
../IMG_7915.PNG,18,1,0,1,1,7,5,4
```

![IMG_7915_R](https://user-images.githubusercontent.com/62515228/87487165-e72b3d80-c677-11ea-8e51-91da8624fb9f.JPG)

paeginfo.py 由来の問題
```
bash-2.03$ python pageinfo.py  IMG_7915_R.JPG
Traceback (most recent call last):
  File "pageinfo.py", line 437, in <module>
    main(args)
  File "pageinfo.py", line 393, in main
    result = look_into_file(filename, args)
  File "pageinfo.py", line 378, in look_into_file
    pagenum, pages, lines = guess_pageinfo(im, args.debug_sc, debug_sc_image)
  File "pageinfo.py", line 331, in guess_pageinfo
    _try_to_detect_scrollbar(im_gray, im_orig_for_debug)
  File "pageinfo.py", line 272, in _try_to_detect_scrollbar
    raise TooManyAreasDetectedError(f'{n} actual scrollbar areas are detected')
__main__.TooManyAreasDetectedError: 2 actual scrollbar areas are detected
```
```
bash-2.03$ python pageinfo.py  ../IMG_7915.PNG
../IMG_7915.PNG,1,1,3
```

**Comment by fgophi** [comment]
pageinfo.py の修正で対応
```
$ fgosccnt  IMG_7915_R.JPG
filename,ドロ数,QP(+6400),礼装,鉄杭,ノーマルダイス,ライフカウンター(x3),ポイントジェム(x3),マーカーハウス(x3)
IMG_7915_R.JPG,18,1,0,1,1,7,5,4
```
