### ISSUE TITLE
自動防衛装置・ハント 典位+級で not valid

### ISSUE THREAD

**Issue by fgophi** [fgophi/fgosccnt#70]
![IMG_0365](https://user-images.githubusercontent.com/62515228/87151151-4d1d6b00-c2ee-11ea-97e5-14aaa053caaa.PNG)
このファイルが not valid になる
```
$ python fgosccnt.py IMG_0365.PNG
filename,ドロ数
IMG_0365.PNG: not valid,
```

**Comment by fgophi** [comment]
右上のドロップ数11の認識で問題が発生しているため
```
$ python fgosccnt.py IMG_0365.PNG
Traceback (most recent call last):
  File "fgosccnt.py", line 1524, in <module>
    csvfieldnames, outputcsv = get_output(inputs, args.debug)
  File "fgosccnt.py", line 1446, in get_output
    sc = ScreenShot(img_rgb, svm, svm_chest, svm_card, debug)
  File "fgosccnt.py", line 402, in __init__
    self.chestnum = self.ocr_tresurechest()
  File "fgosccnt.py", line 621, in ocr_tresurechest
    return int(res)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by fgophi** [comment]
そもそも
読み込んでいる位置が違う
![image](https://user-images.githubusercontent.com/62515228/87151777-6a9f0480-c2ef-11ea-8de4-963ffbc32af5.png)
なぜこんなことが起きているかというとgamescreenの切り出しがおかしい

![game_screen_resize](https://user-images.githubusercontent.com/62515228/87151879-96ba8580-c2ef-11ea-839c-a0c8573b3f6b.png)


なぜ、切り出しがおかしいかというと切り出しのための直線検出で検出されてはいけない直線が検出されているため(最初と二番目の弓猛火ドロップの下部位置)
![line_img](https://user-images.githubusercontent.com/62515228/87152018-df723e80-c2ef-11ea-8a0c-c4eda81b8110.png)

**Comment by fgophi** [comment]
直線検出の
 maxLineGap=8
が悪さをしているので 7以下にすると直る

```
$ python fgosccnt.py IMG_0365.PNG
filename,ドロ数,QP(+9400),火薬,弓魔,弓猛火
IMG_0365.PNG,11,1,3,1,7
```
