### ISSUE TITLE
JPEG化したもののみ not valid

### ISSUE THREAD

**Issue by fgophi** [fgophi/fgosccnt#98]
```
$ fgosccnt IMG_4620_R.JPG
filename,ドロ数
IMG_4620_R.JPG: not valid,
```
```
$ fgosccnt IMG_4620.PNG
filename,ドロ数,チョーク(x3),チョーク(x7),紙片(x3),紙片(x7),ヒポぐるみ(x3)
合計,,2,2,1,1,9
missing,,,,,,
IMG_4620.PNG,15,2,2,1,1,9
```

![IMG_4620_R](https://user-images.githubusercontent.com/62515228/87391130-25c3e800-c5e5-11ea-86b5-f3efe63c113f.JPG)

**Comment by fgophi** [comment]
```
$ fgosccnt  IMG_4620_R.JPG
Traceback (most recent call last):
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 1711, in <module>
    csvfieldnames, outputcsv = get_output(inputs, args.debug)
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 1611, in get_output
    sc = ScreenShot(img_rgb, svm, svm_chest, svm_card, fileextention, debug)
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 421, in __init__
    self.items.append(Item(item_img_rgb, item_img_gray, svm, svm_card, fileextention, mode, debug))
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 778, in __init__
    self.ocr_digit(mode, debug)
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 1308, in ocr_digit
    self.dropnum =  self.detect_white_char(base_line, margin_right, font_size, debug=debug) + self.dropnum
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 1132, in detect_white_char
    line = self.get_number(base_line, margin_right, font_size)
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 1066, in get_number
    result = self.read_char(pt)
  File "c:/Users/nono_000/Documents/git/dev8/fgosccnt/fgosccnt.py", line 1250, in read_char
    tmpimg = cv2.resize(tmpimg, (win_size))
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
```

**Comment by fgophi** [comment]
read_char の読み込み座標がマイナスになっている

JPEG版
```
[133, 152, 153, 180]
[113, 152, 133, 180]
[93, 152, 113, 180]
[64, 152, 84, 180]
[44, 152, 64, 180]
[24, 152, 44, 180]
[-5, 152, 15, 180]
```
PNG版
```
[133, 152, 153, 180]
[153, 152, 173, 180]
[133, 152, 153, 180]
```

**Comment by fgophi** [comment]
アイテムの切り出し位置が一段ずれている
![image](https://user-images.githubusercontent.com/62515228/87393209-c8319a80-c5e8-11ea-8d9c-817b6e90d19c.png)

**Comment by fgophi** [comment]
img2str() のleftcell_ptsの値

- PNG [[15, 614, 203, 816], [15, 387, 203, 589]]
- JPG[ [15, 614, 203, 816]]

PNGは二行目・三行目、JPGは三行目のみ認識

**Comment by fgophi** [comment]
一つしか認識しなくても大丈夫な仕様なのでバグ
